# Generated by Django 5.0.6 on 2024-07-08 10:10

import booking.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('driver', 'Driver')], default='customer', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_no', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)])),
                ('license_no', models.CharField(max_length=50, null=True, unique=True)),
                ('vehicle', models.CharField(max_length=50, null=True)),
                ('vehicle_no', models.CharField(max_length=50, null=True, unique=True)),
                ('wallet', models.FloatField(blank=True, default=0, null=True)),
                ('cancellation_count', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=booking.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('pickup_location', models.CharField(max_length=200, null=True)),
                ('drop_location', models.CharField(max_length=200, null=True)),
                ('pickup_on', models.DateTimeField(auto_now_add=True)),
                ('drop_on', models.DateTimeField(auto_now=True)),
                ('vehicle', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('car', 'Car')], default='bike', max_length=15)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('half_pickup', 'Half_pickup'), ('pickuppoint', 'PickupPoint'), ('pickup', 'Pickup'), ('drop', 'Drop'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('price_per_km', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, default=0, null=True)),
                ('cancellation_fee', models.FloatField(default=0)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('drivers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash_on', 'Cash_on'), ('wallet', 'wallet'), ('creditordebit', 'CreditOrDebit'), ('upi', 'Upi')], default='cash_on', max_length=15)),
                ('paid', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_customer', to='booking.booking')),
            ],
        ),
    ]
