# Generated by Django 5.0.6 on 2024-07-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_user_license_no_alter_user_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=9),
        ),
    ]
